# Generated by Django 4.2.4 on 2023-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published', models.DateField()),
                ('status', models.CharField(choices=[('new', 'NEW'), ('sale', 'SALE')], default='new', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('book_author', models.ManyToManyField(to='book.author')),
                ('genre', models.ManyToManyField(to='book.genre')),
            ],
        ),
    ]
