# Generated by Django 4.0.3 on 2023-08-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_cartitems_alter_book_price_ordereditems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='book_title',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='book_title',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
            preserve_default=False,
        ),
    ]
