# Generated by Django 4.0.3 on 2023-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_cartitems_book_title_cartitems_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='order',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='buy_items',
            field=models.ManyToManyField(to='book.cartitems'),
        ),
    ]
