# Generated by Django 4.0.3 on 2023-09-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_userdetails_birthdate_alter_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='midname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
