# Generated by Django 4.0.3 on 2023-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_userdetails_midname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='book_title',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='book_title',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
