# Generated by Django 4.0.3 on 2023-09-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_cartitems_book_title_cartitems_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='book_title',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='book_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
            preserve_default=False,
        ),
    ]
