# Generated by Django 4.0.3 on 2023-09-11 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0010_remove_cartitems_book_title_cartitems_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='buy_items',
            field=models.ManyToManyField(to='book.order'),
        ),
    ]
