# Generated by Django 4.0.3 on 2023-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_order_alter_ordereditems_buy_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_item',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
