# Generated by Django 4.0.3 on 2023-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_ordereditems_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
