# Generated by Django 4.0.3 on 2023-09-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_publisher_author_author_image_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.publisher'),
            preserve_default=False,
        ),
    ]
