# Generated by Django 4.0.3 on 2023-09-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
