# Generated by Django 4.0.3 on 2023-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('sale', 'SALE'), ('best seller', 'BEST SELLER')], default='new', max_length=20),
        ),
    ]
