# Generated by Django 4.0.3 on 2023-09-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('sale', 'SALE'), ('none', 'NONE')], default='none', max_length=20),
        ),
    ]
