# Generated by Django 4.0.3 on 2023-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wish_book',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wish_book',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
