# Generated by Django 4.0.3 on 2023-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_wishlist_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
