# Generated by Django 4.0.3 on 2023-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images'),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='item_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('order confirm', 'ORDER CONFIRM'), ('out of delivery', 'OUT OF DELIVERY'), ('to received', 'TO RECEIVED'), ('completed', 'COMPLETED')], default='pending', max_length=20),
        ),
    ]
